if(NOT DEFINED DLMS_VERSION_FILE)
  set(DLMS_VERSION_FILE "${CMAKE_CURRENT_LIST_DIR}/../VERSION")
endif()

if(NOT EXISTS "${DLMS_VERSION_FILE}")
  message(FATAL_ERROR "DLMS version file not found: ${DLMS_VERSION_FILE}")
endif()

file(READ "${DLMS_VERSION_FILE}" DLMS_VERSION_RAW)
string(STRIP "${DLMS_VERSION_RAW}" DLMS_VERSION)

if(NOT DLMS_VERSION MATCHES "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?(\\+[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?$")
  message(FATAL_ERROR "Invalid DLMS semantic version '${DLMS_VERSION}'. Expected MAJOR.MINOR.PATCH[-PRERELEASE][+BUILD].")
endif()

set(DLMS_VERSION_MAJOR "${CMAKE_MATCH_1}")
set(DLMS_VERSION_MINOR "${CMAKE_MATCH_2}")
set(DLMS_VERSION_PATCH "${CMAKE_MATCH_3}")
set(DLMS_PROJECT_VERSION "${DLMS_VERSION_MAJOR}.${DLMS_VERSION_MINOR}.${DLMS_VERSION_PATCH}")
